import { StyleSheet } from "react-native";

const colors = {
  textColor: "#000",
  textColor2: "#fff",
  backgroundColor: "#fff",
  tileColor: "#deebfe",
  tileColor2: "#375f96",
};
const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.backgroundColor,
  },
  contentContainer: {
    flexGrow: 1,
    alignItems: "center",
  },
  container: {
    backgroundColor: colors.backgroundColor,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingHorizontal: 25,
    paddingVertical: 10,
    width: "100%",
  },
  toastContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
  },
  titile: {
    marginTop: 10,
    fontSize: 25,
    fontWeight: "bold",
    marginBottom: 30,
  },
  profileIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 75,
    backgroundColor: colors.tileColor,
    borderColor: colors.tileColor2,
    borderWidth: 5,
    width: 100,
    height: 100,
    marginBottom: 20,
  },
  profileImg: {
    width: 100,
    height: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  profileName: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 20,
    marginBottom: 5,
  },
  profileEmail: {
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 30,
  },
  notificationContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 30,
    borderRadius: 20,
    backgroundColor: colors.tileColor,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 5,
  },
  notificationLabel: {
    fontSize: 16,
    fontWeight: "500",
  },

  btnContainer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  btn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 30,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.tileColor,
    backgroundColor: colors.tileColor2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 5,
  },
  btnPressed: {
    backgroundColor: colors.tileColor,
    borderColor: colors.tileColor2,
  },
  buttonText: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "700",
    color: colors.textColor2,
  },
  btnTextchange: {
    color: colors.textColor,
  },
  btn2: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 30,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.tileColor2,
    backgroundColor: colors.tileColor,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 5,
  },
  btnPressed2: {
    backgroundColor: colors.tileColor2,
    borderColor: colors.tileColor,
  },
  buttonText2: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "700",
    color: colors.textColor,
  },
  btnTextchange2: {
    color: colors.textColor2,
  },
});

export default styles;
